name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-unix:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    env:
     CC:   gcc-11
     CXX:  g++-11
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # run the cmake_install.sh script to install using cmake
      run: cmake_install.sh -d ${{github.workspace}}/build -t ${{env.BUILD_TYPE}} -j 1
    
    - name: Archive
      run: tar -czf build.tar.gz build/Release
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.tar.gz
